"""mixup_lambda can be null

Revision ID: 2840a3321663
Revises: 87c3f13e7a4d
Create Date: 2025-01-17 16:48:52.996093

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2840a3321663"
down_revision: Union[str, None] = "87c3f13e7a4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mixup_attrs",
        "mixup_lambda",
        existing_type=mysql.FLOAT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mixup_attrs",
        "mixup_lambda",
        existing_type=mysql.FLOAT(),
        nullable=False,
    )
    # ### end Alembic commands ###
