"""add optional edge weight

Revision ID: 4546a8fd3c43
Revises: bab74799014a
Create Date: 2025-04-22 09:25:24.892713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4546a8fd3c43'
down_revision: Union[str, None] = 'bab74799014a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'weight')
    # ### end Alembic commands ###
