"""add creation time for mixup graphs

Revision ID: 865d94604c93
Revises: 4546a8fd3c43
Create Date: 2025-11-20 18:43:51.029361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "865d94604c93"
down_revision: Union[str, None] = "4546a8fd3c43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mixup_attrs",
        sa.Column("creation_time_us", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mixup_attrs", "creation_time_us")
    # ### end Alembic commands ###
