"""remove mixup_alpha column

Revision ID: 87c3f13e7a4d
Revises: 5dff18d38ce8
Create Date: 2025-01-17 15:44:44.470500

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "87c3f13e7a4d"
down_revision: Union[str, None] = "5dff18d38ce8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mixup_attrs", "mixup_alpha")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mixup_attrs", sa.Column("mixup_alpha", mysql.FLOAT(), nullable=True)
    )
    # ### end Alembic commands ###
