"""add time and estimate to geds

Revision ID: c955aaa639ba
Revises: 436d019ad85e
Create Date: 2025-01-13 11:30:48.325665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c955aaa639ba"
down_revision: Union[str, None] = "436d019ad85e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("geds", sa.Column("time", sa.Integer(), nullable=True))
    op.add_column("geds", sa.Column("estimate", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("geds", "estimate")
    op.drop_column("geds", "time")
    # ### end Alembic commands ###
