"""add mixup_alpha to mixup_attrs

Revision ID: ceb5622e21a7
Revises: c955aaa639ba
Create Date: 2025-01-14 14:45:09.108748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ceb5622e21a7"
down_revision: Union[str, None] = "c955aaa639ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mixup_attrs", sa.Column("mixup_alpha", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mixup_attrs", "mixup_alpha")
    # ### end Alembic commands ###
